# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'posadastodorio.ui'
#
# Created: Thu Apr 07 00:18:13 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(940, 670)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(940, 670))
        MainWindow.setMaximumSize(QtCore.QSize(940, 670))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Users/Lenovo/Desktop/informes/logolista.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setStyleSheet(_fromUtf8("border-color: rgb(58, 63, 158);"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 1011, 641))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(17)
        self.mdiArea.setFont(font)
        self.mdiArea.setStyleSheet(_fromUtf8("border-color: rgb(58, 63, 158);\n"
"background-color: rgb(255, 255, 255);"))
        self.mdiArea.setLineWidth(7)
        self.mdiArea.setActivationOrder(QtGui.QMdiArea.ActivationHistoryOrder)
        self.mdiArea.setViewMode(QtGui.QMdiArea.TabbedView)
        self.mdiArea.setDocumentMode(False)
        self.mdiArea.setTabsClosable(False)
        self.mdiArea.setTabsMovable(False)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.inicio = QtGui.QWidget()
        self.inicio.setObjectName(_fromUtf8("inicio"))
        self.label = QtGui.QLabel(self.inicio)
        self.label.setGeometry(QtCore.QRect(200, 110, 591, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Forte"))
        font.setPointSize(58)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("font: 58pt \"Forte\";\n"
"color: rgb(8, 36, 161);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_45 = QtGui.QLabel(self.inicio)
        self.label_45.setGeometry(QtCore.QRect(800, 570, 101, 16))
        self.label_45.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_44 = QtGui.QLabel(self.inicio)
        self.label_44.setGeometry(QtCore.QRect(340, 210, 281, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.altaproductos = QtGui.QWidget()
        self.altaproductos.setObjectName(_fromUtf8("altaproductos"))
        self.label_3 = QtGui.QLabel(self.altaproductos)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.altaproductos)
        self.label_4.setGeometry(QtCore.QRect(460, 170, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.altaproductos)
        self.label_5.setGeometry(QtCore.QRect(40, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.altaproductos)
        self.label_6.setGeometry(QtCore.QRect(510, 270, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.altaproductos)
        self.label_7.setGeometry(QtCore.QRect(20, 370, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.altaproductos)
        self.label_8.setGeometry(QtCore.QRect(30, 470, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.linecodigo = QtGui.QLineEdit(self.altaproductos)
        self.linecodigo.setGeometry(QtCore.QRect(150, 180, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linecodigo.setFont(font)
        self.linecodigo.setObjectName(_fromUtf8("linecodigo"))
        self.linedescripcion = QtGui.QLineEdit(self.altaproductos)
        self.linedescripcion.setGeometry(QtCore.QRect(590, 180, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linedescripcion.setFont(font)
        self.linedescripcion.setMaxLength(25)
        self.linedescripcion.setObjectName(_fromUtf8("linedescripcion"))
        self.linecantidad = QtGui.QLineEdit(self.altaproductos)
        self.linecantidad.setGeometry(QtCore.QRect(150, 280, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linecantidad.setFont(font)
        self.linecantidad.setMaxLength(6)
        self.linecantidad.setObjectName(_fromUtf8("linecantidad"))
        self.lineprecio = QtGui.QLineEdit(self.altaproductos)
        self.lineprecio.setGeometry(QtCore.QRect(590, 280, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineprecio.setFont(font)
        self.lineprecio.setInputMask(_fromUtf8(""))
        self.lineprecio.setMaxLength(7)
        self.lineprecio.setObjectName(_fromUtf8("lineprecio"))
        self.linebonificacion = QtGui.QLineEdit(self.altaproductos)
        self.linebonificacion.setGeometry(QtCore.QRect(150, 380, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linebonificacion.setFont(font)
        self.linebonificacion.setMaxLength(5)
        self.linebonificacion.setObjectName(_fromUtf8("linebonificacion"))
        self.lineproveedor = QtGui.QLineEdit(self.altaproductos)
        self.lineproveedor.setGeometry(QtCore.QRect(150, 480, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineproveedor.setFont(font)
        self.lineproveedor.setMaxLength(2)
        self.lineproveedor.setObjectName(_fromUtf8("lineproveedor"))
        self.btncancelar = QtGui.QPushButton(self.altaproductos)
        self.btncancelar.setGeometry(QtCore.QRect(490, 560, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btncancelar.setFont(font)
        self.btncancelar.setObjectName(_fromUtf8("btncancelar"))
        self.btnaceptar = QtGui.QPushButton(self.altaproductos)
        self.btnaceptar.setGeometry(QtCore.QRect(700, 560, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnaceptar.setFont(font)
        self.btnaceptar.setObjectName(_fromUtf8("btnaceptar"))
        self.label_2 = QtGui.QLabel(self.altaproductos)
        self.label_2.setGeometry(QtCore.QRect(245, 30, 431, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Forte"))
        font.setPointSize(43)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("font: 43pt \"Forte\";\n"
"color: rgb(8, 36, 161);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_9 = QtGui.QLabel(self.altaproductos)
        self.label_9.setGeometry(QtCore.QRect(380, 90, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_31 = QtGui.QLabel(self.altaproductos)
        self.label_31.setGeometry(QtCore.QRect(420, 380, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.lineobservaciones = QtGui.QLineEdit(self.altaproductos)
        self.lineobservaciones.setGeometry(QtCore.QRect(580, 390, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineobservaciones.setFont(font)
        self.lineobservaciones.setMaxLength(35)
        self.lineobservaciones.setObjectName(_fromUtf8("lineobservaciones"))
        self.altaproveedores = QtGui.QWidget()
        self.altaproveedores.setObjectName(_fromUtf8("altaproveedores"))
        self.linedirpro = QtGui.QLineEdit(self.altaproveedores)
        self.linedirpro.setGeometry(QtCore.QRect(140, 280, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linedirpro.setFont(font)
        self.linedirpro.setMaxLength(25)
        self.linedirpro.setObjectName(_fromUtf8("linedirpro"))
        self.label_10 = QtGui.QLabel(self.altaproveedores)
        self.label_10.setGeometry(QtCore.QRect(50, 170, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.altaproveedores)
        self.label_11.setGeometry(QtCore.QRect(30, 270, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.linecodpro = QtGui.QLineEdit(self.altaproveedores)
        self.linecodpro.setGeometry(QtCore.QRect(140, 180, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linecodpro.setFont(font)
        self.linecodpro.setObjectName(_fromUtf8("linecodpro"))
        self.label_12 = QtGui.QLabel(self.altaproveedores)
        self.label_12.setGeometry(QtCore.QRect(60, 360, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.altaproveedores)
        self.label_13.setGeometry(QtCore.QRect(380, 90, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_15 = QtGui.QLabel(self.altaproveedores)
        self.label_15.setGeometry(QtCore.QRect(460, 270, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineemapro = QtGui.QLineEdit(self.altaproveedores)
        self.lineemapro.setGeometry(QtCore.QRect(140, 370, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineemapro.setFont(font)
        self.lineemapro.setMaxLength(35)
        self.lineemapro.setObjectName(_fromUtf8("lineemapro"))
        self.label_16 = QtGui.QLabel(self.altaproveedores)
        self.label_16.setGeometry(QtCore.QRect(460, 170, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.linenompro = QtGui.QLineEdit(self.altaproveedores)
        self.linenompro.setGeometry(QtCore.QRect(570, 180, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linenompro.setFont(font)
        self.linenompro.setMaxLength(25)
        self.linenompro.setObjectName(_fromUtf8("linenompro"))
        self.linetelpro = QtGui.QLineEdit(self.altaproveedores)
        self.linetelpro.setGeometry(QtCore.QRect(570, 280, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linetelpro.setFont(font)
        self.linetelpro.setMaxLength(25)
        self.linetelpro.setObjectName(_fromUtf8("linetelpro"))
        self.label_17 = QtGui.QLabel(self.altaproveedores)
        self.label_17.setGeometry(QtCore.QRect(245, 30, 431, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Forte"))
        font.setPointSize(43)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet(_fromUtf8("font: 43pt \"Forte\";\n"
"color: rgb(8, 36, 161);"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.btnaceptarpro = QtGui.QPushButton(self.altaproveedores)
        self.btnaceptarpro.setGeometry(QtCore.QRect(720, 560, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnaceptarpro.setFont(font)
        self.btnaceptarpro.setObjectName(_fromUtf8("btnaceptarpro"))
        self.btncancelarpro = QtGui.QPushButton(self.altaproveedores)
        self.btncancelarpro.setGeometry(QtCore.QRect(510, 560, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btncancelarpro.setFont(font)
        self.btncancelarpro.setObjectName(_fromUtf8("btncancelarpro"))
        self.buscarproducto = QtGui.QWidget()
        self.buscarproducto.setObjectName(_fromUtf8("buscarproducto"))
        self.label_28 = QtGui.QLabel(self.buscarproducto)
        self.label_28.setGeometry(QtCore.QRect(245, 30, 431, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Forte"))
        font.setPointSize(43)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet(_fromUtf8("font: 43pt \"Forte\";\n"
"color: rgb(8, 36, 161);"))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_26 = QtGui.QLabel(self.buscarproducto)
        self.label_26.setGeometry(QtCore.QRect(530, 250, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lineproveedorbp = QtGui.QLineEdit(self.buscarproducto)
        self.lineproveedorbp.setEnabled(False)
        self.lineproveedorbp.setGeometry(QtCore.QRect(170, 450, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineproveedorbp.setFont(font)
        self.lineproveedorbp.setObjectName(_fromUtf8("lineproveedorbp"))
        self.label_24 = QtGui.QLabel(self.buscarproducto)
        self.label_24.setGeometry(QtCore.QRect(380, 90, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_23 = QtGui.QLabel(self.buscarproducto)
        self.label_23.setGeometry(QtCore.QRect(40, 350, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_22 = QtGui.QLabel(self.buscarproducto)
        self.label_22.setGeometry(QtCore.QRect(60, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.btnbuscarbp = QtGui.QPushButton(self.buscarproducto)
        self.btnbuscarbp.setGeometry(QtCore.QRect(550, 560, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnbuscarbp.setFont(font)
        self.btnbuscarbp.setObjectName(_fromUtf8("btnbuscarbp"))
        self.linecantidadbp = QtGui.QLineEdit(self.buscarproducto)
        self.linecantidadbp.setEnabled(False)
        self.linecantidadbp.setGeometry(QtCore.QRect(170, 260, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linecantidadbp.setFont(font)
        self.linecantidadbp.setMaxLength(6)
        self.linecantidadbp.setObjectName(_fromUtf8("linecantidadbp"))
        self.linebonificacionbp = QtGui.QLineEdit(self.buscarproducto)
        self.linebonificacionbp.setEnabled(False)
        self.linebonificacionbp.setGeometry(QtCore.QRect(170, 360, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linebonificacionbp.setFont(font)
        self.linebonificacionbp.setMaxLength(7)
        self.linebonificacionbp.setObjectName(_fromUtf8("linebonificacionbp"))
        self.label_27 = QtGui.QLabel(self.buscarproducto)
        self.label_27.setGeometry(QtCore.QRect(480, 150, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_19 = QtGui.QLabel(self.buscarproducto)
        self.label_19.setGeometry(QtCore.QRect(70, 150, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.btncancelarbp = QtGui.QPushButton(self.buscarproducto)
        self.btncancelarbp.setGeometry(QtCore.QRect(350, 560, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btncancelarbp.setFont(font)
        self.btncancelarbp.setObjectName(_fromUtf8("btncancelarbp"))
        self.linedescripcionbp = QtGui.QLineEdit(self.buscarproducto)
        self.linedescripcionbp.setEnabled(False)
        self.linedescripcionbp.setGeometry(QtCore.QRect(610, 160, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linedescripcionbp.setFont(font)
        self.linedescripcionbp.setMaxLength(25)
        self.linedescripcionbp.setObjectName(_fromUtf8("linedescripcionbp"))
        self.linecodigobp = QtGui.QLineEdit(self.buscarproducto)
        self.linecodigobp.setGeometry(QtCore.QRect(170, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linecodigobp.setFont(font)
        self.linecodigobp.setMaxLength(6)
        self.linecodigobp.setObjectName(_fromUtf8("linecodigobp"))
        self.label_25 = QtGui.QLabel(self.buscarproducto)
        self.label_25.setGeometry(QtCore.QRect(50, 450, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.linepreciobp = QtGui.QLineEdit(self.buscarproducto)
        self.linepreciobp.setEnabled(False)
        self.linepreciobp.setGeometry(QtCore.QRect(610, 260, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linepreciobp.setFont(font)
        self.linepreciobp.setMaxLength(7)
        self.linepreciobp.setObjectName(_fromUtf8("linepreciobp"))
        self.btnmodificarbp = QtGui.QPushButton(self.buscarproducto)
        self.btnmodificarbp.setEnabled(False)
        self.btnmodificarbp.setGeometry(QtCore.QRect(740, 560, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnmodificarbp.setFont(font)
        self.btnmodificarbp.setObjectName(_fromUtf8("btnmodificarbp"))
        self.radiobp = QtGui.QRadioButton(self.buscarproducto)
        self.radiobp.setGeometry(QtCore.QRect(340, 160, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.radiobp.setFont(font)
        self.radiobp.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.radiobp.setObjectName(_fromUtf8("radiobp"))
        self.label_41 = QtGui.QLabel(self.buscarproducto)
        self.label_41.setGeometry(QtCore.QRect(450, 350, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.lineobservacionesbp = QtGui.QLineEdit(self.buscarproducto)
        self.lineobservacionesbp.setEnabled(False)
        self.lineobservacionesbp.setGeometry(QtCore.QRect(610, 360, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineobservacionesbp.setFont(font)
        self.lineobservacionesbp.setMaxLength(35)
        self.lineobservacionesbp.setObjectName(_fromUtf8("lineobservacionesbp"))
        self.buscarproveedor = QtGui.QWidget()
        self.buscarproveedor.setObjectName(_fromUtf8("buscarproveedor"))
        self.label_29 = QtGui.QLabel(self.buscarproveedor)
        self.label_29.setGeometry(QtCore.QRect(490, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.buscarproveedor)
        self.label_30.setGeometry(QtCore.QRect(60, 150, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_32 = QtGui.QLabel(self.buscarproveedor)
        self.label_32.setGeometry(QtCore.QRect(40, 250, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.linedireccionbprov = QtGui.QLineEdit(self.buscarproveedor)
        self.linedireccionbprov.setEnabled(False)
        self.linedireccionbprov.setGeometry(QtCore.QRect(150, 260, 280, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linedireccionbprov.setFont(font)
        self.linedireccionbprov.setMaxLength(25)
        self.linedireccionbprov.setObjectName(_fromUtf8("linedireccionbprov"))
        self.linetelefonobprov = QtGui.QLineEdit(self.buscarproveedor)
        self.linetelefonobprov.setEnabled(False)
        self.linetelefonobprov.setGeometry(QtCore.QRect(590, 260, 280, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linetelefonobprov.setFont(font)
        self.linetelefonobprov.setMaxLength(25)
        self.linetelefonobprov.setObjectName(_fromUtf8("linetelefonobprov"))
        self.label_33 = QtGui.QLabel(self.buscarproveedor)
        self.label_33.setGeometry(QtCore.QRect(80, 350, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.btnbuscarbprov = QtGui.QPushButton(self.buscarproveedor)
        self.btnbuscarbprov.setGeometry(QtCore.QRect(530, 560, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnbuscarbprov.setFont(font)
        self.btnbuscarbprov.setObjectName(_fromUtf8("btnbuscarbprov"))
        self.lineemailbprov = QtGui.QLineEdit(self.buscarproveedor)
        self.lineemailbprov.setEnabled(False)
        self.lineemailbprov.setGeometry(QtCore.QRect(150, 360, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineemailbprov.setFont(font)
        self.lineemailbprov.setMaxLength(35)
        self.lineemailbprov.setObjectName(_fromUtf8("lineemailbprov"))
        self.linenombrebprov = QtGui.QLineEdit(self.buscarproveedor)
        self.linenombrebprov.setEnabled(False)
        self.linenombrebprov.setGeometry(QtCore.QRect(590, 160, 280, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linenombrebprov.setFont(font)
        self.linenombrebprov.setMaxLength(25)
        self.linenombrebprov.setObjectName(_fromUtf8("linenombrebprov"))
        self.label_34 = QtGui.QLabel(self.buscarproveedor)
        self.label_34.setGeometry(QtCore.QRect(490, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.btncancelarbprov = QtGui.QPushButton(self.buscarproveedor)
        self.btncancelarbprov.setGeometry(QtCore.QRect(330, 560, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btncancelarbprov.setFont(font)
        self.btncancelarbprov.setObjectName(_fromUtf8("btncancelarbprov"))
        self.linecodigobprov = QtGui.QLineEdit(self.buscarproveedor)
        self.linecodigobprov.setGeometry(QtCore.QRect(150, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linecodigobprov.setFont(font)
        self.linecodigobprov.setMaxLength(2)
        self.linecodigobprov.setObjectName(_fromUtf8("linecodigobprov"))
        self.label_35 = QtGui.QLabel(self.buscarproveedor)
        self.label_35.setGeometry(QtCore.QRect(245, 30, 431, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Forte"))
        font.setPointSize(43)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet(_fromUtf8("font: 43pt \"Forte\";\n"
"color: rgb(8, 36, 161);"))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.buscarproveedor)
        self.label_36.setGeometry(QtCore.QRect(380, 90, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.btnmodificarbprov = QtGui.QPushButton(self.buscarproveedor)
        self.btnmodificarbprov.setEnabled(False)
        self.btnmodificarbprov.setGeometry(QtCore.QRect(720, 560, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnmodificarbprov.setFont(font)
        self.btnmodificarbprov.setObjectName(_fromUtf8("btnmodificarbprov"))
        self.radiobprov = QtGui.QRadioButton(self.buscarproveedor)
        self.radiobprov.setGeometry(QtCore.QRect(310, 160, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.radiobprov.setFont(font)
        self.radiobprov.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.radiobprov.setObjectName(_fromUtf8("radiobprov"))
        self.modificarprecio = QtGui.QWidget()
        self.modificarprecio.setObjectName(_fromUtf8("modificarprecio"))
        self.label_18 = QtGui.QLabel(self.modificarprecio)
        self.label_18.setGeometry(QtCore.QRect(245, 30, 431, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Forte"))
        font.setPointSize(43)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(_fromUtf8("font: 43pt \"Forte\";\n"
"color: rgb(8, 36, 161);\n"
""))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_14 = QtGui.QLabel(self.modificarprecio)
        self.label_14.setGeometry(QtCore.QRect(380, 90, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.linepromp = QtGui.QLineEdit(self.modificarprecio)
        self.linepromp.setGeometry(QtCore.QRect(190, 180, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linepromp.setFont(font)
        self.linepromp.setMaxLength(2)
        self.linepromp.setFrame(True)
        self.linepromp.setObjectName(_fromUtf8("linepromp"))
        self.label_20 = QtGui.QLabel(self.modificarprecio)
        self.label_20.setGeometry(QtCore.QRect(70, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.modificarprecio)
        self.label_21.setGeometry(QtCore.QRect(70, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.linepormp = QtGui.QLineEdit(self.modificarprecio)
        self.linepormp.setGeometry(QtCore.QRect(190, 250, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.linepormp.setFont(font)
        self.linepormp.setInputMask(_fromUtf8(""))
        self.linepormp.setMaxLength(6)
        self.linepormp.setObjectName(_fromUtf8("linepormp"))
        self.listproductos = QtGui.QListWidget(self.modificarprecio)
        self.listproductos.setGeometry(QtCore.QRect(560, 140, 341, 461))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.listproductos.setFont(font)
        self.listproductos.setFrameShape(QtGui.QFrame.StyledPanel)
        self.listproductos.setLineWidth(7)
        self.listproductos.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listproductos.setProperty("isWrapping", False)
        self.listproductos.setLayoutMode(QtGui.QListView.SinglePass)
        self.listproductos.setViewMode(QtGui.QListView.ListMode)
        self.listproductos.setModelColumn(0)
        self.listproductos.setObjectName(_fromUtf8("listproductos"))
        self.btnmodificarmp = QtGui.QPushButton(self.modificarprecio)
        self.btnmodificarmp.setGeometry(QtCore.QRect(190, 380, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnmodificarmp.setFont(font)
        self.btnmodificarmp.setObjectName(_fromUtf8("btnmodificarmp"))
        self.btncancelarmp = QtGui.QPushButton(self.modificarprecio)
        self.btncancelarmp.setGeometry(QtCore.QRect(190, 440, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btncancelarmp.setFont(font)
        self.btncancelarmp.setObjectName(_fromUtf8("btncancelarmp"))
        self.btnverlistamp = QtGui.QPushButton(self.modificarprecio)
        self.btnverlistamp.setGeometry(QtCore.QRect(190, 320, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnverlistamp.setFont(font)
        self.btnverlistamp.setObjectName(_fromUtf8("btnverlistamp"))
        self.label_42 = QtGui.QLabel(self.modificarprecio)
        self.label_42.setGeometry(QtCore.QRect(10, 570, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.listultcam = QtGui.QListWidget(self.modificarprecio)
        self.listultcam.setGeometry(QtCore.QRect(190, 570, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listultcam.setFont(font)
        self.listultcam.setStyleSheet(_fromUtf8("background-color: rgb(232, 227, 232);"))
        self.listultcam.setObjectName(_fromUtf8("listultcam"))
        self.verlistas = QtGui.QWidget()
        self.verlistas.setObjectName(_fromUtf8("verlistas"))
        self.label_37 = QtGui.QLabel(self.verlistas)
        self.label_37.setGeometry(QtCore.QRect(245, 30, 431, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Forte"))
        font.setPointSize(43)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet(_fromUtf8("font: 43pt \"Forte\";\n"
"color: rgb(8, 36, 161);"))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.verlistas)
        self.label_38.setGeometry(QtCore.QRect(420, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.lineprovdes = QtGui.QLineEdit(self.verlistas)
        self.lineprovdes.setGeometry(QtCore.QRect(270, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineprovdes.setFont(font)
        self.lineprovdes.setObjectName(_fromUtf8("lineprovdes"))
        self.lineprovhas = QtGui.QLineEdit(self.verlistas)
        self.lineprovhas.setGeometry(QtCore.QRect(710, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineprovhas.setFont(font)
        self.lineprovhas.setText(_fromUtf8(""))
        self.lineprovhas.setObjectName(_fromUtf8("lineprovhas"))
        self.label_39 = QtGui.QLabel(self.verlistas)
        self.label_39.setGeometry(QtCore.QRect(70, 180, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.verlistas)
        self.label_40.setGeometry(QtCore.QRect(520, 180, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet(_fromUtf8("color: rgb(58, 63, 158);"))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.btnlisproductos = QtGui.QPushButton(self.verlistas)
        self.btnlisproductos.setGeometry(QtCore.QRect(110, 380, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnlisproductos.setFont(font)
        self.btnlisproductos.setObjectName(_fromUtf8("btnlisproductos"))
        self.btnlispropro = QtGui.QPushButton(self.verlistas)
        self.btnlispropro.setGeometry(QtCore.QRect(390, 380, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnlispropro.setFont(font)
        self.btnlispropro.setObjectName(_fromUtf8("btnlispropro"))
        self.btnlisproveedores = QtGui.QPushButton(self.verlistas)
        self.btnlisproveedores.setGeometry(QtCore.QRect(650, 380, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnlisproveedores.setFont(font)
        self.btnlisproveedores.setObjectName(_fromUtf8("btnlisproveedores"))
        self.ayuda = QtGui.QWidget()
        self.ayuda.setEnabled(False)
        self.ayuda.setObjectName(_fromUtf8("ayuda"))
        self.textEdit = QtGui.QTextEdit(self.ayuda)
        self.textEdit.setGeometry(QtCore.QRect(0, 10, 941, 591))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.listproductos.setCurrentRow(-1)
        QtCore.QObject.connect(self.btncancelar, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linecantidad.clear)
        QtCore.QObject.connect(self.btncancelar, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linedescripcion.clear)
        QtCore.QObject.connect(self.btncancelarmp, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linepromp.clear)
        QtCore.QObject.connect(self.btncancelarbp, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linecodigobp.clear)
        QtCore.QObject.connect(self.btncancelar, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linecodigo.clear)
        QtCore.QObject.connect(self.btncancelarpro, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linedirpro.clear)
        QtCore.QObject.connect(self.btncancelarmp, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linepormp.clear)
        QtCore.QObject.connect(self.btncancelarpro, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linetelpro.clear)
        QtCore.QObject.connect(self.btncancelarpro, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linenompro.clear)
        QtCore.QObject.connect(self.btncancelar, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linebonificacion.clear)
        QtCore.QObject.connect(self.btncancelar, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineprecio.clear)
        QtCore.QObject.connect(self.btncancelarpro, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linecodpro.clear)
        QtCore.QObject.connect(self.btncancelar, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineproveedor.clear)
        QtCore.QObject.connect(self.btncancelarpro, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineemapro.clear)
        QtCore.QObject.connect(self.btncancelarbprov, QtCore.SIGNAL(_fromUtf8("clicked()")), self.linecodigobprov.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.linecodigo, self.linedescripcion)
        MainWindow.setTabOrder(self.linedescripcion, self.linecantidad)
        MainWindow.setTabOrder(self.linecantidad, self.lineprecio)
        MainWindow.setTabOrder(self.lineprecio, self.linebonificacion)
        MainWindow.setTabOrder(self.linebonificacion, self.lineobservaciones)
        MainWindow.setTabOrder(self.lineobservaciones, self.lineproveedor)
        MainWindow.setTabOrder(self.lineproveedor, self.btnaceptar)
        MainWindow.setTabOrder(self.btnaceptar, self.btncancelar)
        MainWindow.setTabOrder(self.btncancelar, self.linecodpro)
        MainWindow.setTabOrder(self.linecodpro, self.linenompro)
        MainWindow.setTabOrder(self.linenompro, self.linedirpro)
        MainWindow.setTabOrder(self.linedirpro, self.linetelpro)
        MainWindow.setTabOrder(self.linetelpro, self.lineemapro)
        MainWindow.setTabOrder(self.lineemapro, self.btnaceptarpro)
        MainWindow.setTabOrder(self.btnaceptarpro, self.btncancelarpro)
        MainWindow.setTabOrder(self.btncancelarpro, self.linecodigobp)
        MainWindow.setTabOrder(self.linecodigobp, self.linedescripcionbp)
        MainWindow.setTabOrder(self.linedescripcionbp, self.linecantidadbp)
        MainWindow.setTabOrder(self.linecantidadbp, self.linepreciobp)
        MainWindow.setTabOrder(self.linepreciobp, self.linebonificacionbp)
        MainWindow.setTabOrder(self.linebonificacionbp, self.lineobservacionesbp)
        MainWindow.setTabOrder(self.lineobservacionesbp, self.lineproveedorbp)
        MainWindow.setTabOrder(self.lineproveedorbp, self.btnbuscarbp)
        MainWindow.setTabOrder(self.btnbuscarbp, self.btncancelarbp)
        MainWindow.setTabOrder(self.btncancelarbp, self.btnmodificarbp)
        MainWindow.setTabOrder(self.btnmodificarbp, self.radiobp)
        MainWindow.setTabOrder(self.radiobp, self.linecodigobprov)
        MainWindow.setTabOrder(self.linecodigobprov, self.linenombrebprov)
        MainWindow.setTabOrder(self.linenombrebprov, self.linedireccionbprov)
        MainWindow.setTabOrder(self.linedireccionbprov, self.linetelefonobprov)
        MainWindow.setTabOrder(self.linetelefonobprov, self.lineemailbprov)
        MainWindow.setTabOrder(self.lineemailbprov, self.btnbuscarbprov)
        MainWindow.setTabOrder(self.btnbuscarbprov, self.btncancelarbprov)
        MainWindow.setTabOrder(self.btncancelarbprov, self.btnmodificarbprov)
        MainWindow.setTabOrder(self.btnmodificarbprov, self.radiobprov)
        MainWindow.setTabOrder(self.radiobprov, self.linepromp)
        MainWindow.setTabOrder(self.linepromp, self.linepormp)
        MainWindow.setTabOrder(self.linepormp, self.btnverlistamp)
        MainWindow.setTabOrder(self.btnverlistamp, self.listproductos)
        MainWindow.setTabOrder(self.listproductos, self.btnmodificarmp)
        MainWindow.setTabOrder(self.btnmodificarmp, self.btncancelarmp)
        MainWindow.setTabOrder(self.btncancelarmp, self.listultcam)
        MainWindow.setTabOrder(self.listultcam, self.lineprovdes)
        MainWindow.setTabOrder(self.lineprovdes, self.lineprovhas)
        MainWindow.setTabOrder(self.lineprovhas, self.btnlisproductos)
        MainWindow.setTabOrder(self.btnlisproductos, self.btnlispropro)
        MainWindow.setTabOrder(self.btnlispropro, self.btnlisproveedores)
        MainWindow.setTabOrder(self.btnlisproveedores, self.textEdit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Posadas Todo Rio", None))
        self.inicio.setWindowTitle(_translate("MainWindow", "Inicio", None))
        self.label.setText(_translate("MainWindow", "Posadas Todo Río", None))
        self.label_45.setText(_translate("MainWindow", "Desarrollador: Jespa", None))
        self.label_44.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline; color:#3a3f9e;\">Operaciones del Programa</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">. Inicio<br />. Alta de productos<br />. Alta de proveedores<br />. Buscar productos<br />. Buscar proveedores<br />. Modificar Precio<br />. Ver listas<br />. Ayuda</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p></body></html>", None))
        self.altaproductos.setWindowTitle(_translate("MainWindow", "Alta de productos", None))
        self.label_3.setText(_translate("MainWindow", "Código:", None))
        self.label_4.setText(_translate("MainWindow", "Descripción:", None))
        self.label_5.setText(_translate("MainWindow", "Cantidad:", None))
        self.label_6.setText(_translate("MainWindow", "Precio:", None))
        self.label_7.setText(_translate("MainWindow", "Bonificación:", None))
        self.label_8.setText(_translate("MainWindow", "Proveedor:", None))
        self.linecodigo.setInputMask(_translate("MainWindow", ">A00000; ", None))
        self.lineproveedor.setInputMask(_translate("MainWindow", "00; ", None))
        self.btncancelar.setText(_translate("MainWindow", "Cancelar", None))
        self.btnaceptar.setText(_translate("MainWindow", "Aceptar", None))
        self.label_2.setText(_translate("MainWindow", "Posadas Todo Río", None))
        self.label_9.setText(_translate("MainWindow", "Alta de productos", None))
        self.label_31.setText(_translate("MainWindow", "Observaciones:", None))
        self.altaproveedores.setWindowTitle(_translate("MainWindow", "Alta de proveedores", None))
        self.label_10.setText(_translate("MainWindow", "Código:", None))
        self.label_11.setText(_translate("MainWindow", "Dirección:", None))
        self.linecodpro.setInputMask(_translate("MainWindow", "00; ", None))
        self.label_12.setText(_translate("MainWindow", "Email:", None))
        self.label_13.setText(_translate("MainWindow", "Alta de proveedores", None))
        self.label_15.setText(_translate("MainWindow", "Teléfono:", None))
        self.label_16.setText(_translate("MainWindow", "Nombre:", None))
        self.label_17.setText(_translate("MainWindow", "Posadas Todo Río ", None))
        self.btnaceptarpro.setText(_translate("MainWindow", "Aceptar", None))
        self.btncancelarpro.setText(_translate("MainWindow", "Cancelar", None))
        self.buscarproducto.setWindowTitle(_translate("MainWindow", " Buscar producto", None))
        self.label_28.setText(_translate("MainWindow", "Posadas Todo Río", None))
        self.label_26.setText(_translate("MainWindow", "Precio:", None))
        self.lineproveedorbp.setInputMask(_translate("MainWindow", "##; ", None))
        self.label_24.setText(_translate("MainWindow", "Buscar Productos", None))
        self.label_23.setText(_translate("MainWindow", "Bonificación:", None))
        self.label_22.setText(_translate("MainWindow", "Cantidad:", None))
        self.btnbuscarbp.setText(_translate("MainWindow", "Buscar", None))
        self.label_27.setText(_translate("MainWindow", "Descripción:", None))
        self.label_19.setText(_translate("MainWindow", "Código:", None))
        self.btncancelarbp.setText(_translate("MainWindow", "Cancelar", None))
        self.linecodigobp.setInputMask(_translate("MainWindow", ">A00000; ", None))
        self.label_25.setText(_translate("MainWindow", "Proveedor:", None))
        self.btnmodificarbp.setText(_translate("MainWindow", "Modificar", None))
        self.radiobp.setText(_translate("MainWindow", "Habilitar", None))
        self.label_41.setText(_translate("MainWindow", "Observaciones:", None))
        self.buscarproveedor.setWindowTitle(_translate("MainWindow", "Buscar proveedor", None))
        self.label_29.setText(_translate("MainWindow", "Teléfono:", None))
        self.label_30.setText(_translate("MainWindow", "Código:", None))
        self.label_32.setText(_translate("MainWindow", "Dirección:", None))
        self.label_33.setText(_translate("MainWindow", "Email:", None))
        self.btnbuscarbprov.setText(_translate("MainWindow", "Buscar", None))
        self.label_34.setText(_translate("MainWindow", "Nombre:", None))
        self.btncancelarbprov.setText(_translate("MainWindow", "Cancelar", None))
        self.linecodigobprov.setInputMask(_translate("MainWindow", "00; ", None))
        self.label_35.setText(_translate("MainWindow", "Posadas Todo Río", None))
        self.label_36.setText(_translate("MainWindow", "Buscar Proveedor", None))
        self.btnmodificarbprov.setText(_translate("MainWindow", "Modificar", None))
        self.radiobprov.setText(_translate("MainWindow", "Habilitar", None))
        self.modificarprecio.setWindowTitle(_translate("MainWindow", "Modificar precio", None))
        self.label_18.setText(_translate("MainWindow", "Posadas Todo Río", None))
        self.label_14.setText(_translate("MainWindow", "Modificar Precio", None))
        self.linepromp.setInputMask(_translate("MainWindow", "00; ", None))
        self.label_20.setText(_translate("MainWindow", "Proveedor:", None))
        self.label_21.setText(_translate("MainWindow", "Porcentaje:", None))
        self.btnmodificarmp.setText(_translate("MainWindow", "Modificar precio", None))
        self.btncancelarmp.setText(_translate("MainWindow", "Cancelar", None))
        self.btnverlistamp.setText(_translate("MainWindow", "Ver lista", None))
        self.label_42.setText(_translate("MainWindow", "Últimos cambios:", None))
        self.verlistas.setWindowTitle(_translate("MainWindow", "Ver listas", None))
        self.label_37.setText(_translate("MainWindow", "Posadas Todo Río", None))
        self.label_38.setText(_translate("MainWindow", "Ver listas", None))
        self.lineprovdes.setInputMask(_translate("MainWindow", "00; ", None))
        self.lineprovhas.setInputMask(_translate("MainWindow", "00; ", None))
        self.label_39.setText(_translate("MainWindow", "Proveedor Desde:", None))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p>Proveedor Hasta:</p></body></html>", None))
        self.btnlisproductos.setText(_translate("MainWindow", "Productos", None))
        self.btnlispropro.setText(_translate("MainWindow", "Productos x Proveedor", None))
        self.btnlisproveedores.setText(_translate("MainWindow", "Proveedores", None))
        self.ayuda.setWindowTitle(_translate("MainWindow", "Ayuda", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; text-decoration: underline; color:#3a3f9e;\">Ayuda de Posadas todo Río</span><span style=\" font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#3a3f9e;\">. Alta de Productos: </span><span style=\" font-size:10pt; color:#000000;\">Para ingresar a la pantalla alta de productos hacer clic en la pestaña alta de productos. El primer campo a ingresar es el código del producto. Es un campo alfanumérico de 6 caracters con 1 letra al principio y lugo 5 numeros. Los campos descripción y observación tendran un maximo de 25 y 35 caracteres, la cantidad de 6 caracteres incluyen valores decimales, el precio un maximo de 7 caracteres incluye tambien valores decimales, y la bonificacion una maximo de 5 caracteres incluidos valores decimales. Para introducir valores decimales se hace primero ingresando el punto decimal despues de los valores enteros y luego los dos decimales que desea ingresar. El campo bonificacion es un valor en porcentaje.<br />En los campos  de texto descripcion y observaciones no se puede ingresar la letra ñ y acentos.<br />Si trata de ingresar estos caracteres no se visualizará el mensaje los datos se ingresaron correctamente y no guardará lai información.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">.</span><span style=\" font-size:10pt; color:#3a3f9e;\">Alta de proveedores:</span><span style=\" font-size:10pt; color:#000000;\"> Para ingresar a la pantalla alta de proveedores hacer clic en la pestaña alta de proveedores. El primer campo a ingresar es el codigo de proveedor. Es un campo numérico que puede ser de 1 0 2 digitos. Los campos nombre, dirección, teléfono, email son campos alfanuméricos(letras y números) de 30 caracteres como máximo.<br />En los campos de texto nombre, dirección, teléfono y email no se puede ingresar la letra ñ y acentos. Si trata de ingresar estos caracteres no se visualizará el mensaje los datos se ingresaron correctamente y no guardará lai información.</span><span style=\" font-size:10pt;\"><br /></span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">.</span><span style=\" font-size:10pt; color:#3a3f9e;\">Buscar Productos: </span><span style=\" font-size:10pt; color:#000000;\">Para ingresar a la pantalla hacer clic en la pestaña buscar productos. El primer campo a ingresar es el código de producto. Para buscar por ese campo hacer clic en el botón buscar.  Si ademas desea modificar algunos campos del productos hacer clic en el botón habilitar para que pueda ingresar los cambios . Por último clic en el botón Modificar. En los campos  de texto descripcion y observaciones no se puede ingresar la letra ñ y acentos.<br />Si trata de ingresar estos caracteres  ñ y acentos en la operación modificación, no se visualizará el mensaje los datos se ingresaron correctamente y no modificará lai información.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">.</span><span style=\" font-size:10pt; color:#0000ff;\">Buscar Proveedores: </span><span style=\" font-size:10pt; color:#000000;\">Para ingresar a la pantalla clic en la pestaña buscar proveedores. El proceso es igual a buscar productos. La única diferencia es que se deberá ingresar un codigo de proveedor numérico de uno o dos digitos.  En los campos  de texto nombre, dirección, teléfono y observaciones no se puede ingresar la letra ñ y acentos.<br />Si trata de ingresar estos caracteres  ñ y acentos en la operación modificación, no se visualizará el mensaje los datos se ingresaron correctamente y no modificará lai información.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#0000ff;\">.Modificar Precio: </span><span style=\" font-size:10pt; color:#000000;\">Para ingresar a la pantalla clic en la pestaña modificar precio. Para mostrar la lista de productos hacer clic en ver lista.  Si desea ver la lista de los productos de un  proveedor primero deberá tipear el codigo del proveedor y lugo clic en ver lista.  En la casilla precio deberá ingresar ingresar el porcentaje de aumento de precio de los productos. Luego seleccionara los produtos que recibiran los cambios de precios con el boton derecho del mouse y pulsando simultaneamente la tecla ctrl.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">.</span><span style=\" font-size:10pt; color:#3a3f9e;\">Ver listas: </span><span style=\" font-size:10pt; color:#000000;\">Para ingresar a la pantalla clic en la pestaña ver listas. Para ver la lista de todos los productos hacer clic en productos. Si desar ver la lista de los productos de proveedores ingresar el proveedor desde y el proveedor hasta y clic en el boton productos x proveedor.  Para ver la lista de proveedores ingresar el proveedor desde y hasta y clic en el botón proveedores.</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"><br /></span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"><br /></span></p></body></html>", None))

